---
- name: Query an Open API
  hosts: localhost
  connection: local

  vars:
      networklist: 'http://api.citybik.es/v2/networks'

  tasks:
  - name: Send an HTTP GET to API
    ansible.builtin.uri:
      method: GET
      url: "{{ networklist }}"
    register: data

  - name: Use debug to show what is inside of our variable
    ansible.builtin.debug:
      msg: "{{ data }}"

  - name: Slice the variable further to only return the JSON
    ansible.builtin.debug:
      msg: "{{ data.get('json').get('networks').get('company') }}"

        #  - name: Use debug with a loop across the JSON data
        #ansible.builtin.debug:
        #msg: "On the {{ item.get('company') }} is: {{ item.get('id') }}"
        #loop: "{{ data.get('json').get('city') }}"

